server:
  port: 8080      # which port your Spring Boot app runs on

spring:
  datasource:
    url: jdbc:postgresql://localhost:5334/postgres   # where your database is
      # localhost = your machine
      # 5334 = the port from docker-compose
    # postgres = database name
    username: root              # must match POSTGRES_USER in docker-compose
    password: password          # must match POSTGRES_PASSWORD in docker-compose
  jpa:
    hibernate:
      ddl-auto: update     # creates tables when app starts, drops them when it stops
      # use "update" when you don't want to lose data on restart
    properties:
      hibernate:
        format_sql: true        # makes SQL logs readable
    show-sql: true              # prints every SQL query in the console

spotify:
  client-id: 47534b62a8a34fc7ab3301968c1f936d
  client-secret: c83f0d7b41264eb68cea2bbe228b85ec