server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5334/postgres
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

spotify:
  client-id: your_client_id_here
  client-secret: your_client_secret_here